CELLCorpus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.urlpatterns import format_suffix_patterns
from concordance import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^concordance', include('concordance.urls')),
    url(r'^viewConcordance/', views.ConcordanceList.as_view()),
    url(r'^viewFrequency/', views.FrequencyList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

LearnerCorpus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.urlpatterns import format_suffix_patterns
from concordance import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^corpus/index', include('concordance.urls')),
    url(r'^viewConcordance/', views.ConcordanceList.as_view()),
    url(r'^viewFrequency/', views.FrequencyList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

concordance/urls.py
from django.conf.urls import url
from . import views

app_name = 'concordance'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
]

concordance/models.py
from django.db import models

class Concordance(models.Model):
    search_word = models.CharField(max_length=50)
    concord = models.CharField(max_length=250)

    def __str__(self):
        return self.search_word


class Corpus(models.Model):
    corpus_name = models.CharField(max_length=250)
    corpus_type= models.CharField(max_length=250)
    corpus_file = models.FileField()

    def __str__(self):
        return self.corpus_name

concordance/views.py
# from django.shortcuts import render
# from django.shortcuts import get_object_or_404
# from nltk.book import text1
from rest_framework.views import APIView
from rest_framework.response import Response
# from rest_framework import status
# from .models import Corpus
# from .serializers import ConcordanceSerializer
# from nltk.corpus import *
from nltk.text import Text
from django.views import generic
from CELLCorpus.settings import CORPUS_ROOT
from nltk import FreqDist
# from django.http import JsonResponse


class HomeView(generic.ListView):
    template_name = 'concordance/home.html'
    def get_queryset(self):
        return ""

class IndexView(generic.ListView):
    template_name = 'concordance/index.html'
    def get_queryset(self):
        return ""

# List all Concordances for the given word
class ConcordanceList(APIView):

    # Return all Concordances
    def get(self, request):
        # Open and Read the txt files
        corpusFile = open(CORPUS_ROOT + "a1.txt", 'rU', encoding="utf8")
        corpusFileRead = corpusFile.read()
        # ftext1 = corpusFileRead.split()
        abst = Text(corpusFileRead.split())
        result = (abst.concordance_list(str(request.GET.get('param'))))
        return Response(result)

    def post(self):
        pass


# List the frequencis of most common word
class FrequencyList(APIView):

    # Return all Concordances
    def get(self, request):
        # Open and Read the txt files
        corpusFile = open(CORPUS_ROOT + "a1.txt", 'rU', encoding="utf8")
        corpusFileRead = corpusFile.read()
        abst = Text(corpusFileRead.split())

        fdist1 = FreqDist(abst)
        result = fdist1.most_common(50)
        return Response(result)

    def post(self):
        pass

concordance/templates/concordance/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Corpus{% endblock %}</title>

    <!-- Loads the path to your static files -->
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">

    <!--<link rel="stylesheet" type="text/css" href="/concordance/static/corpusapp/style.css"/>-->
    <link rel="stylesheet" type="text/css" href="{% static 'concordance/style.css' %}"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--<script src="/concordance/static/corpusapp/Scripts/Utils.js"></script>-->
     <script src="{% static 'concordance/Scripts/Utils.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'concordance:index' %}">Concordance</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <div class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input id="search_word" type="text" class="form-control" name="q" value=""placeholder="Enter Word">
                </div>
                <button type="button" class="btn btn-default" onclick="corpus.getConcordance()">Find Concordance</button>
                <button type="button" class="btn btn-default" onclick="corpus.getFrequency()">Find Frequency</button>
            </div>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}


</body>
</html>

concordance/templates/concordance/home.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>CELL Corpus </title>
  
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'concordance/CSS/bootstrap.min.css' %}"/>
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" type="text/css" href="{% static 'concordance/CSS/mdb.min.css' %}"/>
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" type="text/css" href="{% static 'concordance/CSS/styleNew.css' %}"/>
  <style type="text/css">
    html,
    body,
    header,
    .view {
      height: 100%;
    }

    @media (max-width: 559px) {
      html,
      body,
      header,
      .view {
        height: 1000px;
      }
    }

    @media (min-width: 560px) and (max-width: 740px) {
      html,
      body,
      header,
      .view {
        height: 700px;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {
      html,
      body,
      header,
      .view {
        height: 600px;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {
            .navbar:not(.top-nav-collapse) {
                background: #1C2331!important;
            }
        }
  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand" href="concordance" target="_blank">
        <strong>CELL Corpus</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="concordance" target="_blank">E&L Corpus</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="concordance" target="_blank">HKEAA Corpus</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="concordance" target="_blank">Archives</a>
          </li>
        </ul>
      </div>

    </div>
  </nav>
  <!-- Navbar -->

  <!-- Full Page Intro -->
  <div class="view">

    <video class="video-intro" poster="{% static 'concordance/images/backgroundNew.jpg' %}" playsinline autoplay muted loop>
      <source src="{% static 'concordance/images/Lines-min.mp4' %}" type="video/mp4">
    </video>

    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

      <!-- Content -->
      <div class="text-center white-text mx-5 wow fadeIn">

        <h1 class="display-5 mb-3">
          <strong>The Chinese and English Learner Language Corpus(CELL Corpus) is a corpus supported by an IDS grant funded by the Research Grants Council of the Hong Kong Special Administrative Region, China (Project Code: UGC/IDS16/17)</strong>
        </h1>

      </div>
      <!-- Content -->

    </div>

  </div>
  <!-- Full Page Intro -->

  <!--Footer-->
  <footer class="page-footer text-center font-small wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
    </div>
    <!--/.Call to action-->
    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/cellcorpusouhk" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>
      <a href="https://twitter.com/cellcorpusouhk" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>
      <a href="https://github.com/cellcorpusouhk" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>
      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>
    </div>

    <!--Copyright-->
    <div class="footer-copyright py-3"> © 2018 RIBiLT OUHK </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src= " {% static 'concordance/Scripts/jquery-3.3.1.min.js' %} "></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src= "{% static 'concordance/Scripts/popper.min.js' %} "></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'concordance/Scripts/bootstrap.min.js' %}"></script>
</body>

</html>

concordance/templates/concordance/index.html
{% extends 'concordance/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid" id="concordance_display">
    <table>
        <tbody id="tbody"></tbody>
    </table>
</div>
{% endblock %}